### ISSUE TITLE
Promise based wrapper for Acknowledgements with inferred type

### ISSUE THREAD

**Issue by panwauu** [socketio/socket.io-client#1511] opened 2021-10-27 18:23 UTC
I am using typed events. An example can be seen here:
```ts
export interface ClientToServerEvents {
  'testEvent': (testData: number, cb: (data: returnData) => void) => void,
}
```

I want to use the Acknowledgement-Functionality. Thus I wrap the .emit in a new Promise. The result of the callback-Function res is inferred but it does not infer the type of the promise. So the Promise is typed Promise<unknown> although the type returnData is inferred for the res.

```ts
const promise = new Promise((resolve) => {
  const timeout = setTimeout(() => { reject(new Error("Socket.io Acknowledgement timed out")) }, 1000)

  socket.emit("testEvent", 1, (res) => {
    clearTimeout(timeout)
    resolve(res)
  });
});
```

This solution does not infer types which is suboptimal but also writing this everytime is alot of overhead.
It would be nice to just call it like below and get a promise with the correct return type (with optional timeout).

```ts
const promise = socket.emitWithAck("testEvent", 1, timeout)
// Typed automatically as Promise<returnData>
```
Do you have any better way to write this?

**Comment by darrachequesne** [comment] 2021-11-03 21:10
Closed as duplicate of https://github.com/socketio/socket.io/discussions/4144.

**Closed by darrachequesne** 2021-11-03 21:10 UTC
Labels: enhancement
