### ISSUE TITLE
inconsistent typing and actual export structure would cause runtime error using with webpack and typescript [v3.0.0]

### ISSUE THREAD

**Issue by noe132** [socketio/socket.io-client#1396] opened 2020-11-09 09:15 UTC
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
When using with webpack and typescript,
```ts
import { io } from 'socket.io-client';
```
is valid for typescript, but would result an error in runtime.
because when typescript looks for typing, it gets `build/index.d.ts`,
and webpack try resolve path for the package, and it looks `package.json`, and found there is field `["exports"]["."]["import"]` and use its value `./wrapper.mjs`, but has an different export structure than the typing above.

### Steps to reproduce (if the current behaviour is a bug)
Setup a minimal webpack ts-loader build, and using `io` would get this error message

### Expected behaviour
warpper.mjs should have same export structure as build/index.js

### Setup
- OS: win10
- browser: chrome 86
- socket.io version: 3.0.0

**Comment by Tallyrald** [comment] 2020-11-09 10:32
My problem is probably caused by this so I'll just comment here instead of opening another ticket:
Before v3.0.0 I could do this:
```typescript
import SocketIO from 'socket.io-client';
let socket = SocketIO.connect('some URL string', { transports: ['websocket'] });
```
Now I can't. v3.0.1 exposes only 4 properties: protocol, Manager, io, Socket. No methods or subproperties in any of them. Am I missing something? Did the usage pattern change, but it's missing from the changelog?
I'm using Typescript v4.0.5

**Comment by darrachequesne** [comment] 2020-11-09 10:49
@Tallyrald you should be able to use:

```ts
import { io }  from 'socket.io-client';

let socket = io('some URL string', { transports: ['websocket'] });
```

I think we should have removed the `connect()` method in v3, as it's just an alias.

@noe132 I could indeed reproduce the issue, as CommonJS and ES module definitions are out of sync.

**Comment by Tallyrald** [comment] 2020-11-09 11:00
Oh, you're completely correct, it seems my train of thoughts derailed somewhere between the version upgrade and the seemingly missing exports. Everything is fine, thank you!

**Comment by ShaneMcGowan** [comment] 2020-11-17 09:22
Having the same issue. Was starting a new project using socket.io and socket.io-client.

### Set Up
    OS: win10
    browser: chrome 86
    socket.io version: 3.0.0

### Issue
Webpack is complaining and saying
```export 'io' (imported as 'io') was not found in 'socket.io-client'```

### Work Around
Downgrading to V2.3.1 allowed webpack to bundle everything together and run without issue

**Comment by mgroenhoff** [comment] 2020-11-18 14:53
I'm now getting this error when doing `import { io } from "socket.io-client";` in my code which is bundled using webpack:

```
ERROR in ./node_modules/socket.io-client/wrapper.mjs 4:13
Module parse failed: Identifier 'io' has already been declared (4:13)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export const Manager = io.Manager;
> export const io = io;
| export default io;
|
```

**Comment by darrachequesne** [comment] 2020-11-20 01:55
This should be fixed in `socket.io-client@3.0.3`.

Closed by https://github.com/socketio/socket.io-client/commit/bec15240ea67e9d296ac94093974d7d831239e8d.

**Closed by darrachequesne** 2020-11-20 01:55 UTC
Labels: bug
