### ISSUE TITLE
socket.io-client libray  Build issue  in Angular 7.1  

### ISSUE THREAD

**Issue by rsurendraidexcel** [socketio/socket.io-client#1524] opened 2022-01-14 14:35 UTC
Hi i got this kind of issue  while run the angular 7.1 project  

![Error](https://user-images.githubusercontent.com/7713535/149532496-35db2629-3e63-468e-88e7-d30c7df14c0f.jpg)

Type script 3.1.6 version
Any body  have idia this kind of issue

**Comment by darrachequesne** [comment] 2022-01-15 06:37
Duplicate of https://github.com/socketio/socket.io/discussions/4251.

**Closed by darrachequesne** 2022-01-15 06:37 UTC
Labels: bug
