### ISSUE TITLE
SSL Connection broken.

### ISSUE THREAD

**Issue by jagould2012** [socketio/socket.io-client#986] opened 2016-08-11 17:22 UTC
We are currently using this module with node to connect to a server that uses a private CA issued cert. The client side uses the ssl-root-cas module to insert the server CA cert prior to connecting. This works up to 1.4.5, but fails on 1.4.6 and above. Any ideas on what changed in 1.4.6 and on?

Error from 1.4.6 and above:

 { [Error: unable to verify the first certificate]
    code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
    type: 'error',
    target: 
     WebSocket {
       domain: null,
       _events: [Object],
       _eventsCount: 4,
       _maxListeners: undefined,
       _socket: null,
       _ultron: null,
       _closeReceived: false,
       bytesReceived: 0,
       readyState: 0,
       supports: [Object],
       extensions: {},
       _isServer: false,
       url: <<URL REMOVED>>,
       protocolVersion: 13,
       binaryType: 'buffer' } } }

**Comment by PsyTae** [comment] 2016-08-15 14:12
similar to #982

**Comment by darrachequesne** [comment] 2016-11-23 15:03
Closed as duplicate of https://github.com/socketio/socket.io-client/issues/982.

**Closed by darrachequesne** 2016-11-23 15:03 UTC
