### ISSUE TITLE
cli undefined error on "error" event

### ISSUE THREAD

**Issue by JohnMcLear** [socketio/socket.io-client#819] opened 2015-02-16 22:13 UTC
When I test this simple connection script:

```
var io = require('socket.io-client');
var serverUrl = 'http://localhost:9001';
var socket = io.connect(serverUrl);

socket.on('error', function(e){
  console.log("error", e)
});
```

This is the output:

```
jose@PBOH-SNUG:~/etherpad-socketio-client$ node app.js
error undefined
```

Expected Output: 
A useful error message.

Versions:
node 10.33
socket.io-client 1.3.4

Other thoughts..  None of the below events are firing:

```
socket.on('connect', function(data){
  console.log("c", data);
});
socket.on('event', function(data){
  console.log("e", data);
});
socket.on('disconnect', function(data){
  console.log("d", data);
});
socket.on('connect_error', function(data){
  console.log("ce", data)
});
socket.on('connect_timeout', function(data){
  console.log("ct", data)
});
```

**Comment by JohnMcLear** [comment] 2015-02-16 22:33
Correct syntax is 

```
  var socket = require('socket.io-client')('http://localhost');
```
not 
```
var serverUrl = 'http://localhost:9001';
var socket = io.connect(serverUrl);
```

**Comment by JohnMcLear** [comment] 2015-02-16 22:34
Hrm yet I still don't get a connection error or error..  I just got "silence"...

```
^Cjose@PBOH-SNUG:~/etherpad-socketio-client$ node app.js
error undefined undefined
```

So that makes me think Etherpad is silently dropping the connection

**Comment by JohnMcLear** [comment] 2015-02-16 22:37
Hrm yeah I'm pretty sure error should be populated if it's firing...

**Comment by nkzawa** [comment] 2015-03-09 15:15
I couldn't reproduce the issue. How can I do that?

**Comment by marcopadillo** [comment] 2016-01-06 09:12
I'm also experiencing this. Running a node app on port 3002. Was able to replicate it by doing this:
```
var io = require('socket.io-client');
var socket = io.connect('http://localhost:3002');

socket.on('error', function(data) {
    console.log('error', data);
});
```

**Comment by darrachequesne** [comment] 2021-01-25 15:57
That should be fixed now, thanks.

**Closed by darrachequesne** 2021-01-25 15:57 UTC
Labels: Unable to reproduce
