### ISSUE TITLE
Socket.io - Client 3.0.0+ reconnect event all failed

### ISSUE THREAD

**Issue by newpanjing** [socketio/socket.io-client#1432] opened 2020-12-30 08:14 UTC
Socket.io - Client 3.0.0+ reconnect event all failed.

Switch to version 2.3.1 and it works.

```javascript
const io = require('socket.io-client');

let socket = io.connect('ws://127.0.0.1:8000', {
    "transports": ['websocket', 'polling'],
    reconnection: true
});
socket.on('connect', function(data){
    onlineFlag = true;
    console.log(data + ' - connect');
});
socket.on('connect_error', function(data){
    console.log(data + ' - connect_error');
});
socket.on('connect_timeout', function(data){
    console.log(data + ' - connect_timeout');
});
socket.on('error', function(data){
    console.log(data + ' - error');
});
socket.on('disconnect', function(data){
    onlineFlag = false;
    console.log(data + ' - disconnect');
});
socket.on('reconnect', function(data){
    console.log(data + ' - reconnect');
});
socket.on('reconnect_attempt', function(data){
    console.log(data + ' - reconnect_attempt');
});
socket.on('reconnecting', function(data){
    console.log(data + ' - reconnecting');
});
socket.on('reconnect_error', function(data){
    console.log(data + ' - reconnect_error');
});
socket.on('reconnect_failed', function(data){
    console.log(data + ' - reconnect_failed');
});
socket.on('ping', function(data){
    console.log(data + ' - ping');
});
socket.on('pong', function(data){
    console.log(data + ' - pong');
});
```

**Comment by tannerkrewson** [comment] 2021-01-01 21:31
I had this issue too; I figured it out!! It's by design:

https://socket.io/docs/v3/migrating-from-2-x-to-3-0/index.html#The-Socket-instance-will-no-longer-forward-the-events-emitted-by-its-Manager

**Comment by darrachequesne** [comment] 2021-01-02 21:31
@newpanjing hi! What do you mean by "reconnect event all failed" ? 

As pointed out by @tannerkrewson (thanks!), the Socket instance no longer emits any reconnection events.

```js
// no longer emitted
socket.on("reconnect_attempt", () => {});
// but you can listen to the events emitted by the Manager instance (the io attribute)
socket.io.on("reconnect_attempt", () => {});
```

**Comment by tannerkrewson** [comment] 2021-01-02 22:38
Would it be possible to have a warning message in the console if someone tries to use those events on the socket itself? I think that would be super helpful for people migrating, instead of it silently failing.  😄

**Comment by jrj2211** [comment] 2021-02-11 01:51
I too agree this is kind of confusing. I thought I could listen for reconnect directly on the socket and not socket.io. Would be nice if there was a warning if you try to use an unknown event for socket like @tannerkrewson suggested. Looking back at the documentation though, I clearly didn't read. There are multiple stackoverflows that suggest reconnect works directly on the socket object.

**Comment by darrachequesne** [comment] 2021-02-11 10:50
I'm not sure that adding a warning is a good idea, because users can actually use the "reconnect" event.

I've added a note in the documentation, to make it clearer: https://socket.io/docs/v3/client-socket-instance/#Events

I'm going to close this for now, please reopen if needed.

**Closed by darrachequesne** 2021-02-11 10:50 UTC
Labels: question
