### ISSUE TITLE
angular-cli problem running ng-test

### ISSUE THREAD

**Issue by holtc** [socketio/socket.io-client#1136] opened 2017-06-18 16:52 UTC
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
I have an angular-cli project setup.  In my package.json `dependencies` section, I have `"socket.io-client":^"2.0.3"`.  When I run `ng serve`, the project runs fine, but when I try to run `ng test`, I get the following error:

`Cannot find module 'socket.io-client/dist/socket.io.min.js'`

I checked in the `node_modules` folder, and that file indeed does not exist.  There is a `socket.io-client/dist/socket.io.js` file that looks minified though, along with a map file.  Is this an error and the file should be named `.min.js`?  Do you know why `ng test` is looking for the file here?  Thanks!

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS: Ubuntu 16.04
- browser: 
- socket.io version: 2.0.3

**Comment by darrachequesne** [comment] 2017-06-19 10:48
Could you please check your version of `socket.io`? I think this is a duplicate of https://github.com/socketio/socket.io-client/issues/1130.

**Comment by holtc** [comment] 2017-06-19 13:34
I currently have not run `npm install socket.io` in that project, but I have run `npm install socket.io-client` and the version is 2.0.3.  Do I need to also install `socket.io`?

**Comment by vreelb** [comment] 2017-06-27 23:30
This appears to be the same issue as #1130
I am having it as well using version 2.0.3
It appears that the minified files were deleted in d30914d11b13e51ce1c1419d5cc99a74df72c2a7, causing them to be unavailable despite being looked for. It should be as simple as minifying the file and adding it back into dist/

**Comment by vreelb** [comment] 2017-07-24 02:41
Any update on this? Currently I have to rename .slim.js to .min.js and things work just fine, but it's a pain to have to include that in the install instructions.

**Comment by dolanmiu** [comment] 2017-10-24 00:32
I am having this issue on `2.0.4`

**Comment by jorgeriv** [comment] 2018-08-01 23:40
This issue still happening in version "2.1.1", has anyone found a better solution than renaming .slim.js to min.js ?

**Comment by linasbumbulis** [comment] 2018-08-02 13:17
Check your node_modules folder. Find socket.io-client and check the version on package.json file. Compare it with the version of socket.io itself, it should be the same. For me it was 1.7.4 so I added socket.io@2.1.1 along with the socket.io-client@2.1.1 in my package.json file so that it would forcibly download socket.io 2.1.1 instead of the one defined in socket.io-client package.

In short, add both socket.io-client and socket.io in your package.json with versions of 2.1.1.

**Comment by darrachequesne** [comment] 2021-01-28 12:35
That should be fixed now, thanks.

**Closed by darrachequesne** 2021-01-28 12:35 UTC
