### ISSUE TITLE
Calling `manager.disconnect()` before a socket is created fails

### ISSUE THREAD

**Issue by ianstormtaylor** [socketio/socket.io-client#1315] opened 2019-08-02 00:29 UTC
If you create a manager using the `Manager` api directly, and then call `manager.disconnect()` before any sockets are created with `manager.socket()`:

```js
const manager = new Manager('/', { ... })
manager.disconnect()
```

It will show a warning in DevTools and no future calls to `manager.connect()` will seemingly get it to start working again. But it also doesn't seem to know it's disconnected? Hard to tell, but it breaks.

Ideally using `disconnect/connect` should be allowed in any state without breakage. I'm using the manager directly because I'd like to control connection status across all sockets when the tab loses visibility.

Maybe I'm not understanding something?

**Comment by darrachequesne** [comment] 2024-04-10 13:46
For future readers:

I was not able to reproduce the issue, it might have been fixed in a recent release:

```js
import { Manager } from "socket.io-client";

const manager = new Manager(`http://localhost:3000`);

manager.disconnect();

setTimeout(() => {
  const socket = manager.socket("/");

  socket.on("connect", () => {
    console.log(`connect ${socket.id}`);
  });

  socket.on("connect_error", (err) => {
    console.log(`connect_error due to ${err.message}`);
  });
}, 1000);
```

Please reopen if needed.

**Closed by darrachequesne** 2024-04-10 13:46 UTC
