### ISSUE TITLE
Client reconnect to server doesn't function as instructed.

### ISSUE THREAD

**Issue by ethernetweb** [socketio/socket.io-client#1067] opened 2017-02-09 06:16 UTC
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

I hesitate to bring up what appears to be an old issue that was resolved but I'm now experiencing it in a new version.
I have a socket.io server and a socket.io-client
Both version 1.7.2

When the server calls socket.disconnect(), the client will disconnect but not reconnect, even with the option of reconnection:true
I have attempted to use a disconnect handler client-side to call socket.io.reconnect() but this does nothing.
The socket object reports skipReconnect = true after being disconnected by the server.

Server side disconnect event:  server namespace disconnect
Client side disconnect event: io server disconnect

### Steps to reproduce (if the current behaviour is a bug)

1. Client connection to server. Established OK.
2. Server calls socket.disconnect(); Both client and server close the connection and event handlers discover it.
3. Client will not reconnect automatically, even with reconnection:true or directly calling socket.io.reconnect();

https://github.com/ethernetweb/socket.io-fiddle/

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour

With the option of reconnection:true, client should attempt a reconnect with established socket object within the reconnectionDelay time-frame.

### Setup
- OS: Debian 8.7
- browser: not applicable
- socket.io version: 1.7.2

**Comment by centrual** [comment] 2017-02-23 19:09
I have same issue too.

**Comment by akleiner2** [comment] 2017-03-29 04:00
+1

**Comment by kmyllyvi** [comment] 2017-04-20 12:32
I have this issue also. Has anyone found a workaround to reconnect. I get the 'reconnect' event but the connection is not established. Calling open() or connect() hasn't helped.

Also the timeout value doesn't seem to correlate to actual timeout at least when running on Android/iOS webview (Angular2 webapp). Socket disconnects after latest 2-3min of inactivity even my timeout on client side is set to 18000000 (30min if I'm not mistaken).

**Comment by darrachequesne** [comment] 2017-04-22 11:55
@ethernetweb you should be able to reconnect manually with `socket.connect()`.

I guess it makes sense not to automatically reconnect by default, since it is a deliberate action from the server.

**Comment by kmyllyvi** [comment] 2017-04-26 08:33
Yes you might be right. I managed to connect manually after idle disconnect.

Like so:

**Comment by bogdancochioras** [comment] 2017-05-05 11:51
after rebooting my master server, the client server reconnect is not called and calling after disconnecting and calling connect manually does not connect, same problem as @kmyllyvi

**Comment by darrachequesne** [comment] 2017-06-01 11:09
@bogdancochioras could you please open a new issue and provide some code reproducing the issue please?

Closing this one, see my answer [below](https://github.com/socketio/socket.io-client/issues/1067#issuecomment-296368319).

**Closed by darrachequesne** 2017-06-01 11:09 UTC
