### ISSUE TITLE
on('disconnect') handler called twice after `disconnect()` if immediately followed by a `connect()`

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io-client#860] opened 2015-07-14 15:34 UTC
It looks like `socket.connect()`is causing the second disconnect handler to fire. Perhaps this is because if you call `connect()` immediately after disconnecting, it's actually not done disconnecting. 

Wrapping `connect()` after the `disconnect()` in a `setTimeout()` with a delay of 0 will result in one disconnection event occurring in total.

I'm not sure if there's a better way to reconnect, `reconnect()` isn't in the public API . I know you can do `socket.io.engine.close()` and it will automatically reconnect. Also:

`socket.io.disconnect();`
`socket.io.skipReconnect = false;`
`socket.io.reconnect();`

will work, but notice that you need to set `skipReconnect`. These are also private API functions.

How can I reconnect without having the disconnect handler run twice? Also note that wrapping the `connect()` in a `setTimeout()` will not trigger the reconnect handler (but disconnecting and connecting with no `setTimeout()` will).

**Comment by nkzawa** [comment] 2016-01-16 16:33
I could reproduce the issue, thanks.

**Comment by rob-cam3l** [comment] 2021-01-02 17:49
This might be 5 years old but i am posting a comment in the case that it might help someone else.

I just spent two weeks looking at every possibly solution to this problem in the end i did the following. 

I was manually disconnecting the socket with socket.disconnect(), change the query parameters of the socket object (this is just because of the functionality i am implementing) and then manually reconnecting immediately after using socket.connect() and was always getting two (or more) connection events server side.

*Old code*
`let socket = io.connect()

function updateData() {

     socket.disconnect();

     socket.io.opts.query = {
                     dataToBeUpdated: newData
                 }

     socket.connect();
}
`

This code was resulting in the server side getting two connections, one that contained the old information and one that contained the new information, and on manual termination of the application would log the client has disconnected, but it also logged EVERY client that had connected after the data had been updated, so if the socket was updated 10 times and then the client side app was terminated it would log each of the 10 sockets as disconnected. 

I tried every solution i could find and eventually changing the 
`socket.disconnect()`
event to a 
`socket.io.disconnect()` but KEEPING socket.connect() the same solved the issue. Now only one example of the client is ever connected to the server after the information has been updated. 

I hope someone somewhere finds this information helpful!

**Comment by darrachequesne** [comment] 2022-04-13 06:42
For future readers:

This should be fixed by https://github.com/socketio/socket.io-client/commit/99c2cb8421361487ed7c876edd8670bb69a5c5b5, included in `socket.io-client@4.4.0`.

**Closed by darrachequesne** 2022-04-13 06:42 UTC
Labels: bug

**Comment by Albertyhu** [comment] 2024-01-28 02:48
I am also experiencing the same problem. The version of my socket.io package is 4.7.4.

**Comment by darrachequesne** [comment] 2024-01-29 17:07
@Albertyhu this is a very old issue. Could you please open a new issue with all necessary details? Thanks!
